### ISSUE TITLE
java.lang.Throwable: Failed to read file [/var/folders/d8/_fsb_h0j1qz_s5rkwb2cfhsw0000gn/T/ide_github_workflow_plugin/_checkout_actions_checkout__v3_checkout_schema.json] message [/var/folders/d8/_fsb_h0j1qz_s5rkwb2cfhsw0000gn/T/ide_github_workflow_plugin/_checkout_actions_checkout__v3_checkout_schema.json]

### ISSUE THREAD

**Issue by hche608** [YunaBraska/github-workflow-plugin#13]
### Steps to Reproduce
Please provide code sample if applicable

### Runtime Information
Plugin version : 2.2.6
IDE: IntelliJ IDEA 2023.2 (IU-232.8660.185)
OS: macOS 13.3.1

### Stacktrace
```
java.lang.Throwable: Failed to read file [/var/folders/d8/_fsb_h0j1qz_s5rkwb2cfhsw0000gn/T/ide_github_workflow_plugin/_checkout_actions_checkout__v3_checkout_schema.json] message [/var/folders/d8/_fsb_h0j1qz_s5rkwb2cfhsw0000gn/T/ide_github_workflow_plugin/_checkout_actions_checkout__v3_checkout_schema.json]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.github.yunabraska.githubworkflow.completion.GitHubWorkflowUtils.readFileAsync(GitHubWorkflowUtils.java:291)
	at com.github.yunabraska.githubworkflow.completion.GitHubWorkflowUtils.downloadContent(GitHubWorkflowUtils.java:265)
	at com.github.yunabraska.githubworkflow.completion.GitHubWorkflowUtils.downloadAction(GitHubWorkflowUtils.java:206)
	at com.github.yunabraska.githubworkflow.model.GitHubAction.setActionParameters(GitHubAction.java:214)
	at com.github.yunabraska.githubworkflow.model.GitHubAction.resolve(GitHubAction.java:184)
	at com.github.yunabraska.githubworkflow.listeners.ApplicationStartup$1.run(ApplicationStartup.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:477)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by YunaBraska** [comment]
I will make the cache & download method more defensive.
@hche608 do you have also the cause of the stack trace, or is this all? Would be interesting to know why the file load failed

**Comment by YunaBraska** [comment]
The new Version [2.2.7](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/383062) (will be public in few days) will fix this.
