### ISSUE TITLE
Unhandled exception in [CoroutineName(com.github.yunabraska.githubworkflow.services.ProjectStartup), StandaloneCoroutine{Cancelling}@356f15cb, Dispatchers.Default]

### ISSUE THREAD

**Issue by cgrabmann** [YunaBraska/github-workflow-plugin#31]
### Description
Hi I just opened 3 Projects and this error was then reported by IntelliJ. I don't know much more sry.

### Steps to Reproduce
Please provide code sample if applicable

### Message
*** exception class was changed or removed

### Runtime Information
Plugin version : 3.0.0
IDE: IntelliJ IDEA 2023.2.2 (IU-232.9921.47)
OS: Windows 10.0

### Stacktrace
```
  Unhandled exception in [CoroutineName(com.github.yunabraska.githubworkflow.services.ProjectStartup), StandaloneCoroutine{Cancelling}@356f15cb, Dispatchers.Default]
  
  java.lang.StringIndexOutOfBoundsException: begin 83, end 79, length 93
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
at java.base/java.lang.String.substring(String.java:2709)
at com.github.yunabraska.githubworkflow.model.GitHubAction.createGithubAction(GitHubAction.java:87)
at com.github.yunabraska.githubworkflow.services.GitHubActionCache.lambda$get$3(GitHubActionCache.java:84)
at java.base/java.util.Optional.orElseGet(Optional.java:364)
at com.github.yunabraska.githubworkflow.services.GitHubActionCache.get(GitHubActionCache.java:83)
at com.github.yunabraska.githubworkflow.services.GitHubActionCache.lambda$getAction$16(GitHubActionCache.java:172)
at java.base/java.util.Optional.map(Optional.java:260)
at com.github.yunabraska.githubworkflow.services.GitHubActionCache.getAction(GitHubActionCache.java:172)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
at com.github.yunabraska.githubworkflow.services.ProjectStartup.lambda$asyncInitAllActions$7(ProjectStartup.java:98)
at java.base/java.util.Optional.ifPresent(Optional.java:178)
at com.github.yunabraska.githubworkflow.services.ProjectStartup.lambda$asyncInitAllActions$8(ProjectStartup.java:98)
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
at com.github.yunabraska.githubworkflow.services.ProjectStartup.asyncInitAllActions(ProjectStartup.java:95)
at com.github.yunabraska.githubworkflow.services.ProjectStartup.asyncInitAllActionsAfterInit(ProjectStartup.java:85)
at com.github.yunabraska.githubworkflow.services.ProjectStartup.execute(ProjectStartup.java:51)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invokeSuspend(StartupManagerImpl.kt:534)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:532)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.github.yunabraska.githubworkflow.services.ProjectStartup), StandaloneCoroutine{Cancelled}@356f15cb, Dispatchers.Default]
```

**Comment by YunaBraska** [comment]
Thank you.
It sounds like there is a workflow file which I can't handle.
Is it only happening when you open multiple projects, or is it only happening on one project and a specific workflow file?
I will have a look into it.

**Comment by cgrabmann** [comment]
I just tried to open one after the other and then there is no problem. Also started them up again in a bulk and also no problem, so might be some concurrency issue?

**Comment by YunaBraska** [comment]
Wow, that's interesting. Thanks for the info. I will have a look if I can reproduce it and if not I will just make that piece concurrent

**Comment by YunaBraska** [comment]
Version [3.0.2](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/412502) is on the way 🎉.
It doesn't look like a concurrency issue, it looks more like a missing check on an edge case when you misspell a something in the `uses` value like `user/repo@/.yml`

**Comment by YunaBraska** [comment]
Its released. Can you check again if the issue is gone?

**Comment by cgrabmann** [comment]
I used it the last 2 days and the Exception did not happen anymore 👍 

I'm gonna close this.
Thanks
