### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"sessionId":"2080387763","projectHash":"7ce5a137","ranges":[{"exclusiveRef":"An-overview-of-the-days-showing","inclusiveRef":"origin/An-overview-of-the-days-showing"}],"roots":[{"path":"C:/Users/Najam/OneDrive - Københavns Erhvervsakademi/KEA/KinoXp"}]}

### ISSUE THREAD

**Issue by najamoe** [YunaBraska/github-workflow-plugin#32]
### Steps to Reproduce
Please provide code sample if applicable

### Runtime Information
Plugin version : 3.0.1
IDE: IntelliJ IDEA 2023.2.2 (IU-232.9921.47)
OS: Windows 11.0

### Stacktrace
```
java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"sessionId":"2080387763","projectHash":"7ce5a137","ranges":[{"exclusiveRef":"An-overview-of-the-days-showing","inclusiveRef":"origin/An-overview-of-the-days-showing"}],"roots":[{"path":"C:/Users/Najam/OneDrive - Københavns Erhvervsakademi/KEA/KinoXp"}]}
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.github.yunabraska.githubworkflow.model.schema.DependabotSchemaProvider.lambda$isAvailable$0(DependabotSchemaProvider.java:28)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.github.yunabraska.githubworkflow.model.schema.DependabotSchemaProvider.isAvailable(DependabotSchemaProvider.java:28)
	at com.github.yunabraska.githubworkflow.services.FileIconProvider.lambda$getIcon$0(FileIconProvider.java:22)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at com.github.yunabraska.githubworkflow.services.FileIconProvider.getIcon(FileIconProvider.java:22)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProviderIcon(IconUtil.kt:226)
	at com.intellij.util.IconUtil.computeFileIconImpl(IconUtil.kt:167)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.kt:159)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:392)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:391)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by YunaBraska** [comment]
Thx, i will have a look on it

**Comment by YunaBraska** [comment]
Thanks for reporting, the Version [3.0.3](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/413303) including fix is on the way. The issue was, that I missed migrating the file schema files to the new IDE cache implementation.

**Comment by YunaBraska** [comment]
The new version is rolled out now. Can you test if the issue is still there?

**Comment by YunaBraska** [comment]
No answer, I guess it means that the issue is solved
