### ISSUE TITLE
URL too long

### ISSUE THREAD

**Issue by lazarljubenovic** [YunaBraska/github-workflow-plugin#45]
**What happened?**
My WebStorm crashed for (I think) unrelated reasons. Upon reopening, there was a red bell at the bottom-right, and I clicked it. I've clicked "Report and clear" without really reading the thing, so I can't tell you much about that.

Anyway, my Chrome opened about 15 pages, all of which pointed to a "URL too long" GitHub page. Here's one URL that I've saved.

### Runtime Information
Plugin version : 3.1.0
IDE: WebStorm 2023.2.4 (WS-232.10203.14)
OS: Linux 6.2.0-36-generic

### Stacktrace
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=JSFile:StorageApi.ts, file.class=class com.intellij.lang.javascript.psi.impl.JSFileImpl, file.lang=Language: TypeScript, modStamp=1
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
 viewProvider=com.intellij.lang.javascript.JSFileViewProviderFactory$JSFileViewProvider{vFile=file:///home/lazar/elements-web/src/sdk/src/apis/StorageApi.ts, vFileId=665542, content=VirtualFileContent{size=147305}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1700581347986; file length: 147305
 doc saved: true; doc stamp: 0; doc size: 147305; committed: true
indexing info: indexing timestamp = 1700581330785, binary = false, byte size = 149645, char size = 149645
ref: 50cf572587cf
latestIndexedStub=null
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:203)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.lambda$createCompleteException$0(StubTreeLoader.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.createCompleteException(StubTreeLoader.java:177)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:228)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:727)
	at com.intellij.psi.impl.source.PsiFileImpl.getChildren(PsiFileImpl.java:732)
	at com.github.yunabraska.githubworkflow.helper.PsiElementHelper.getAllElements(PsiElementHelper.java:290)
	at com.github.yunabraska.githubworkflow.helper.PsiElementHelper.getAllElements(PsiElementHelper.java:291)
	at com.github.yunabraska.githubworkflow.helper.PsiElementHelper.getAllElements(PsiElementHelper.java:282)
	at com.github.yunabraska.githubworkflow.helper.PsiElementChangeListener.lambda$childrenChanged$3(PsiElementChangeListener.java:33)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.github.yunabraska.githubworkflow.helper.PsiElementChangeListener.childrenChanged(PsiElementChangeListener.java:33)
	at com.intellij.psi.impl.PsiManagerImpl.notifyPsiTreeChangeListener(PsiManagerImpl.java:407)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:350)
	at com.intellij.psi.impl.PsiManagerImpl.childrenChanged(PsiManagerImpl.java
```

It's up to you if you want to dedicate this issue to the "too long" part or the actual problem part. I really have no idea what happened and nothing was really disrupted in my workflow. I didn't even have a single yaml file open at the time.

**Relevant log output**
Uuuh see URL?

**Operating System**
Ubuntu 22.04

**Plugin Version**
3.1.0, update to 3.2.1 pending (not installed -- will do now)

**IDE Name and Version**
WebStorm 2023.2.4
Build #WS-232.10203.14, built on October 25, 2023

**Comment by YunaBraska** [comment]
Hi, thanks for reporting. Unfortunately, I can't give any support for an older version.
The thing is, that the older version is scanning unfortunately all files also `node_modules` which is really too much, and then it's also blocking. That's fixed in the newer version. The best and easiest way is to update to the newer version ;)

**Comment by lazarljubenovic** [comment]
Sure! Thought you might want to know that the URLs are too long sometimes and that might mean missing some feedback completely.

It feels like I've installed it just yesterday. They grow up so quickly 🥲 Cheers! 🍻

**Comment by YunaBraska** [comment]
Ah yes, you are right, i have to do something about the too long URL :)
