### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.github.yunabraska.githubworkflow.model.GitHubAction.isSuppressed()" because "action" is null

### ISSUE THREAD

**Issue by zwj-cheer** [YunaBraska/github-workflow-plugin#50]
### Steps to Reproduce
Please provide code sample if applicable

### Runtime Information
Plugin version : 3.2.1
IDE: WebStorm 2023.3.1 (WS-233.11799.293)
OS: macOS 14.1.1

### Stacktrace
```
java.lang.NullPointerException: Cannot invoke "com.github.yunabraska.githubworkflow.model.GitHubAction.isSuppressed()" because "action" is null
	at com.github.yunabraska.githubworkflow.services.ProjectStartup.lambda$asyncInitAllActions$4(ProjectStartup.java:90)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.github.yunabraska.githubworkflow.services.ProjectStartup.lambda$asyncInitAllActions$6(ProjectStartup.java:90)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.github.yunabraska.githubworkflow.services.ProjectStartup.lambda$asyncInitAllActions$7(ProjectStartup.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.github.yunabraska.githubworkflow.services.ProjectStartup.lambda$asyncInitAllActions$8(ProjectStartup.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by YunaBraska** [comment]
Due to significant changes introduced by JetBrains, my plugin now faces numerous disruptions. After dedicating substantial effort to this project last year, I find myself needing assistance to move forward. If you're interested in contributing or know someone who might be, please feel free to get involved. I am available to provide guidance through the intricacies of the plugin.
