### ISSUE TITLE
IDE Internal Errors: IntelliJ Community got an error 

### ISSUE THREAD

**Issue by zaaraungkam** [YunaBraska/github-workflow-plugin#70]
**What happened?**
IDE : Intellij show an error with "Exeption in plugin Github Workflow(1.0.1) This plugin is not production of JetBrains ...

**How can we reproduce the issue?**
1.Install the plugin
2. Start the Intellij

**Relevant log output**
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:608)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:359)
	at com.intellij.util.io.HttpRequests$RequestImpl.doReadBytes(HttpRequests.java:435)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:424)
	at com.intellij.util.io.RequestBuilder.lambda$readString$4(RequestBuilder.java:81)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:81)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:85)
	at com.github.yunabraska.githubworkflow.completion.GitHubWorkflowUtils.lambda$downloadContent$7(GitHubWorkflowUtils.java:271)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:328)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Operating System**
Window

**Plugin Version**
1.0.1

**IDE Name and Version**
Intellij community version  2022.2.3

**Expected behavior**
can use workflow suggestion syntax as normal

**Screenshots**

**Additional context**

**Comment by YunaBraska** [comment]
Thanks for the timeout stack trace. Slow or failed downloads now return unresolved metadata without raising an IDE error; timeout behavior is covered by a regression test. Closing as fixed for the upcoming release.
